#!/usr/bin/env bash
# Set the terminal title and prompt

# Get prompt_git() from git_prompts
. $HOME/.config/shell/prompt-git

if tput setaf 1 &> /dev/null; then
	tput sgr0; # reset colors
	bold=$(tput bold);
	reset=$(tput sgr0);
	# Solarized colors, taken from http://git.io/solarized-colors.
	black=$(tput setaf 0);
	blue=$(tput setaf 33);
	cyan=$(tput setaf 37);
	green=$(tput setaf 64);
	orange=$(tput setaf 166);
	purple=$(tput setaf 125);
	red=$(tput setaf 124);
	violet=$(tput setaf 61);
	white=$(tput setaf 15);
	yellow=$(tput setaf 136);
else
	bold='';
	reset="\e[0m";
	black="\e[1;30m";
	blue="\e[1;34m";
	cyan="\e[1;36m";
	green="\e[1;32m";
	orange="\e[1;33m";
	purple="\e[1;35m";
	red="\e[1;31m";
	violet="\e[1;35m";
	white="\e[1;37m";
	yellow="\e[1;33m";
fi;

# Default user/host colors
userStyle="${white}";
hostStyle="${cyan}";
# Highlight the user name when logged in as root.
[[ "$USER" == "root" ]] && userStyle="${red}";
# Highlight the hostname when connected via SSH.
[[ -n "$SSH_CLIENT" ]] && hostStyle="${yellow}";

# Set the terminal title and prompt.
PS1="\[\033]0;\W\007\]"; # working directory base name
PS1+="\[${bold}\]\n"; # newline
PS1+="\[${userStyle}\u"; # username
PS1+="\[${hostStyle}\]@";
PS1+="\[${hostStyle}\]\h"; # host
PS1+="\[${hostStyle}\]:";
PS1+="\[${hostStyle}\]\w"; # working directory
PS1+="\$(prompt_git \"\[${white}\] on \[${violet}\]\" \"\[${blue}\]\")"; # Git repository details
PS1+="\[${reset}\]\n"; # newline
#PS1+="\[${yellow}\][\t]"; # timestamp
PS1+="\[${white}\]$ \[${reset}\]"; # `$` (and reset color)
export PS1;

PS2="\[${yellow}\]→ \[${reset}\]";
export PS2;
